//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnpLoans.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityUser
    {
        public int SecurityUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int UserTypeID { get; set; }
        public string Email { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
