//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnpLoan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityUser
    {
        public int SecurityUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserTypeId { get; set; }
        public string Email { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
